version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: energy_manager
      MYSQL_ROOT_PASSWORD: password # your root password
    volumes:
      # absolute path to the init script - the script name (specify package it lives within) + :/docker-entrypoint-initdb.d
      - /Users/nadashetty/CFG+Masters/code/assignments/final-project/Java-Masters-Final-Project-group-1/src/main/resources/database:/docker-entrypoint-initdb.d

  green-energy-manager:
    # please change the below value to the sha256 img hash for green-energy-manager from docker desktop
    image: ab98ed1e5def252ce92047df6f45b00ab3e362d8b7c930aecbbe411ee0498268
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/energy_manager
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password